name: flutter_app_template
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Logger
  simple_logger:

  # LocalDatabase
  shared_preferences:

  # Riverpod
  flutter_hooks:
  hooks_riverpod:

  # Entity
  freezed_annotation:
  json_annotation:
  equatable:

  # Dialog
  adaptive_dialog:

  # Access local storage
  path_provider:

  # Date
  intl: 0.18.0

  # Reactive
  rxdart:

  # Data share
  share_plus:

  # WebView
  flutter_inappwebview:

  # Launcher
  url_launcher:
  map_launcher:

  # Transition
  page_transition:

  # Image
  image_picker:
  image_gallery_saver:
  image_cropper:
  flutter_image_compress:

  # TODO ビルドエラー対応
  extended_image:
    git:
      url: https://github.com/SuaMusica/extended_image.git
      ref: feature/flutter310

  flutter_svg:

  # Picker
  numberpicker:

  # PullToRefresh
  pull_to_refresh_flutter3:

  # Permission
  permission_handler:

  # Firebase
  firebase_core: ^2.11.0
  firebase_analytics: ^10.3.0
  cloud_firestore: ^4.6.0
  firebase_auth: ^4.5.0
  firebase_storage: ^11.1.2
  cloud_functions: ^4.2.0
  firebase_messaging: ^14.5.0
  firebase_crashlytics: ^3.2.0
  firebase_remote_config: ^4.1.0

  # LocalNotification
  flutter_local_notifications: ^14.0.0+1
  flutter_native_timezone:
  timezone:

  # Api
  retrofit:
  dio:

  # Navigation
  go_router: ^7.0.0

  # Info
  package_info_plus:
  device_info_plus:

  # Text
  flutter_linkify:

  # Widget
  flutter_slidable:
  dismissible_page:

  # Other
  uuid:
  synchronized:
  hashids2:
  recase:
  collection:
  quiver:
  html:

  # TODO ビルドエラー対応
  macos_ui:
    git:
      url: https://github.com/Mayb3Nots/macos_ui
      ref: dev

# TODO firebase_auth_web と flutter_localizations が参照するバージョンが異なるため暫定対応
dependency_overrides:
  intl: 0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis
  pedantic_mono: ^1.21.1

  # Serializer
  json_serializable:

  # Code generator
  build_runner:
  freezed: ^2.3.3
  flutter_gen_runner:
  retrofit_generator:

  # Other
  flutter_launcher_icons:

flutter_gen:
  output: lib/gen/
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # カスタムフォントを利用する場合はここを設定する
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# flutter_launcher_iconsを利用してアイコンのリサイズする場合はここを設定する
#flutter_icons:
#  android: true
#  ios: true
#  image_path_android: "assets/icon/icon_android.png"
#  image_path_ios: "assets/icon/icon_ios.png"
#  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
#  adaptive_icon_background: "#F4A281"

