name: flutter_app_template
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Logger
  simple_logger:

  # LocalDatabase
  shared_preferences:

  # Riverpod
  flutter_hooks:
  hooks_riverpod:
  freezed_annotation:
  json_annotation:

  # Dialog
  adaptive_dialog:

  # Access local storage
  path_provider:

  # Date
  intl:

  # Reactive
  rxdart:

  # Data share
  share_plus:

  # WebView
  flutter_inappwebview:

  # Launcher
  url_launcher:
  map_launcher:

  # Setting
  app_settings:

  # Review
  launch_review:
  in_app_review:

  # Text
  auto_size_text:

  # Carousel
  carousel_slider:

  # Switch
  toggle_switch:

  # Transition
  page_transition:

  # Image
  image_picker:
  image_gallery_saver:
  image_cropper:
  flutter_image_compress:
  extended_image:

  # Picker
  numberpicker:

  # PullToRefresh
  pull_to_refresh_flutter3:

  # Scroll
  extended_nested_scroll_view: ^6.0.0

  # Permission
  permission_handler:

  # Firebase
  firebase_core: ^2.10.0
  firebase_analytics: ^10.2.1
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.1
  cloud_functions: ^4.1.1
  firebase_messaging: ^14.4.1
  firebase_crashlytics: ^3.1.1
  firebase_remote_config: ^4.0.1

  # LocalNotification
  flutter_local_notifications: 14.0.0-dev.4
  flutter_native_timezone:

  # Api
  retrofit:
  dio:

  # Navigation
  go_router: ^6.5.7

  # Widget
  flutter_fadein:
  flutter_cupertino_datetime_picker:
  flutter_app_badger:
  badges:
  flutter_slidable:
  dismissible_page:

  # Other
  equatable:
  uuid:
  package_info_plus:
  device_info_plus:
  synchronized:
  nonce:
  crypto:
  hashids2:
  encrypt:
  flutter_svg:
  recase:
  flutter_linkify:
  timezone:
  collection:
  quiver:
  html:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis
  pedantic_mono: ^1.21.1

  # Serializer
  json_serializable:

  # Code generator
  build_runner:
  freezed: ^2.3.2
  flutter_gen_runner:
  retrofit_generator:

  # Other
  flutter_launcher_icons:

flutter_gen:
  output: lib/gen/
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # カスタムフォントを利用する場合はここを設定する
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# flutter_launcher_iconsを利用してアイコンのリサイズする場合はここを設定する
#flutter_icons:
#  android: true
#  ios: true
#  image_path_android: "assets/icon/icon_android.png"
#  image_path_ios: "assets/icon/icon_ios.png"
#  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
#  adaptive_icon_background: "#F4A281"

