targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true # false -> true
          explicit_to_json: true # false -> true
      freezed:
        generate_for:
          include:
            - lib/core/entities/*.dart
            - lib/core/entities/**/*.dart
            - lib/features/**/entities/*.dart
            - lib/features/**/entities/**/*.dart